# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConductedCalibration.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 601, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startCal_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startCal_pushButton.setObjectName("startCal_pushButton")
        self.horizontalLayout.addWidget(self.startCal_pushButton)
        self.freq_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.freq_label.setObjectName("freq_label")
        self.horizontalLayout.addWidget(self.freq_label)
        self.freq_lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.freq_lcdNumber.setObjectName("freq_lcdNumber")
        self.horizontalLayout.addWidget(self.freq_lcdNumber)
        self.power_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.power_label.setObjectName("power_label")
        self.horizontalLayout.addWidget(self.power_label)
        self.power_lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.power_lcdNumber.setObjectName("power_lcdNumber")
        self.horizontalLayout.addWidget(self.power_lcdNumber)
        self.voltage_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.voltage_label.setObjectName("voltage_label")
        self.horizontalLayout.addWidget(self.voltage_label)
        self.voltage_lcdNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.voltage_lcdNumber.setObjectName("voltage_lcdNumber")
        self.horizontalLayout.addWidget(self.voltage_lcdNumber)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.graph_graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.graph_graphicsView.setObjectName("graph_graphicsView")
        self.verticalLayout.addWidget(self.graph_graphicsView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startCal_pushButton.setText(_translate("MainWindow", "Start Calibration"))
        self.freq_label.setText(_translate("MainWindow", "Frequency:"))
        self.power_label.setText(_translate("MainWindow", "Power:"))
        self.voltage_label.setText(_translate("MainWindow", "Voltage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
